// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace baseA_admixture_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 81> locations_array__ =
  {" (found before start of program)",
  " (in 'baseA_admixture.stan', line 33, column 4 to column 39)",
  " (in 'baseA_admixture.stan', line 34, column 4 to column 21)",
  " (in 'baseA_admixture.stan', line 35, column 4 to column 22)",
  " (in 'baseA_admixture.stan', line 36, column 4 to column 22)",
  " (in 'baseA_admixture.stan', line 37, column 4 to column 27)",
  " (in 'baseA_admixture.stan', line 44, column 6 to column 31)",
  " (in 'baseA_admixture.stan', line 43, column 19 to line 45, column 5)",
  " (in 'baseA_admixture.stan', line 43, column 4 to line 45, column 5)",
  " (in 'baseA_admixture.stan', line 46, column 4 to column 24)",
  " (in 'baseA_admixture.stan', line 47, column 4 to column 25)",
  " (in 'baseA_admixture.stan', line 48, column 4 to column 26)",
  " (in 'baseA_admixture.stan', line 49, column 4 to column 28)",
  " (in 'baseA_admixture.stan', line 53, column 6 to column 18)",
  " (in 'baseA_admixture.stan', line 99, column 8 to column 109)",
  " (in 'baseA_admixture.stan', line 100, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 98, column 10 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 95, column 8 to column 149)",
  " (in 'baseA_admixture.stan', line 96, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 94, column 48 to line 97, column 7)",
  " (in 'baseA_admixture.stan', line 94, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 90, column 8 to column 149)",
  " (in 'baseA_admixture.stan', line 91, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 89, column 48 to line 92, column 7)",
  " (in 'baseA_admixture.stan', line 89, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 85, column 8 to column 127)",
  " (in 'baseA_admixture.stan', line 86, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 84, column 48 to line 87, column 7)",
  " (in 'baseA_admixture.stan', line 84, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 80, column 8 to column 168)",
  " (in 'baseA_admixture.stan', line 81, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 79, column 48 to line 82, column 7)",
  " (in 'baseA_admixture.stan', line 79, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 75, column 8 to column 268)",
  " (in 'baseA_admixture.stan', line 76, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 74, column 48 to line 77, column 7)",
  " (in 'baseA_admixture.stan', line 74, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 70, column 8 to column 69)",
  " (in 'baseA_admixture.stan', line 71, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 69, column 48 to line 72, column 7)",
  " (in 'baseA_admixture.stan', line 69, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 65, column 8 to column 69)",
  " (in 'baseA_admixture.stan', line 66, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 64, column 48 to line 67, column 7)",
  " (in 'baseA_admixture.stan', line 64, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 60, column 8 to column 119)",
  " (in 'baseA_admixture.stan', line 61, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 59, column 48 to line 62, column 7)",
  " (in 'baseA_admixture.stan', line 59, column 11 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 55, column 8 to column 109)",
  " (in 'baseA_admixture.stan', line 56, column 8 to column 51)",
  " (in 'baseA_admixture.stan', line 54, column 43 to line 57, column 7)",
  " (in 'baseA_admixture.stan', line 54, column 6 to line 101, column 7)",
  " (in 'baseA_admixture.stan', line 51, column 23 to line 102, column 5)",
  " (in 'baseA_admixture.stan', line 51, column 4 to line 102, column 5)",
  " (in 'baseA_admixture.stan', line 24, column 2 to column 21)",
  " (in 'baseA_admixture.stan', line 25, column 18 to column 23)",
  " (in 'baseA_admixture.stan', line 25, column 2 to column 27)",
  " (in 'baseA_admixture.stan', line 26, column 18 to column 23)",
  " (in 'baseA_admixture.stan', line 26, column 2 to column 27)",
  " (in 'baseA_admixture.stan', line 27, column 8 to column 13)",
  " (in 'baseA_admixture.stan', line 27, column 2 to column 26)",
  " (in 'baseA_admixture.stan', line 28, column 8 to column 13)",
  " (in 'baseA_admixture.stan', line 28, column 2 to column 27)",
  " (in 'baseA_admixture.stan', line 29, column 2 to column 14)",
  " (in 'baseA_admixture.stan', line 3, column 8 to column 35)",
  " (in 'baseA_admixture.stan', line 4, column 8 to column 135)",
  " (in 'baseA_admixture.stan', line 5, column 8 to column 38)",
  " (in 'baseA_admixture.stan', line 6, column 8 to column 24)",
  " (in 'baseA_admixture.stan', line 2, column 56 to line 7, column 5)",
  " (in 'baseA_admixture.stan', line 9, column 8 to column 32)",
  " (in 'baseA_admixture.stan', line 10, column 8 to column 32)",
  " (in 'baseA_admixture.stan', line 11, column 8 to column 102)",
  " (in 'baseA_admixture.stan', line 12, column 8 to column 101)",
  " (in 'baseA_admixture.stan', line 13, column 8 to column 27)",
  " (in 'baseA_admixture.stan', line 14, column 8 to column 27)",
  " (in 'baseA_admixture.stan', line 8, column 68 to line 15, column 5)",
  " (in 'baseA_admixture.stan', line 17, column 8 to column 32)",
  " (in 'baseA_admixture.stan', line 18, column 8 to column 32)",
  " (in 'baseA_admixture.stan', line 19, column 8 to column 98)",
  " (in 'baseA_admixture.stan', line 16, column 64 to line 20, column 5)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
p_L_divide_l(const T0__& N, const T1__& t1, const T2__& t2, const T3__& l,
             std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>,
                              stan::math::disjunction<stan::is_autodiff<T4__>,
                                                      std::is_floating_point<T4__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
int_p_L_divide_l(const T0__& N, const T1__& t1, const T2__& t2, const T3__&
                 u, const T4__& v, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
int_p_L_divide_l_limit(const T0__& N, const T1__& t, const T2__& u,
                       const T3__& v, std::ostream* pstream__);
// real p_L_divide_l(real, real, real, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
p_L_divide_l(const T0__& N, const T1__& t1, const T2__& t2, const T3__& l,
             std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ c = DUMMY_VAR__;
    current_statement__ = 65;
    c = -(((l / 50) + (1 / N)));
    local_scalar_t__ output = DUMMY_VAR__;
    current_statement__ = 66;
    output = (((stan::math::exp((c * t2)) * ((stan::math::pow((c * t2), 2) -
      ((2 * c) * t2)) + 2)) / stan::math::pow(c, 3)) -
      ((stan::math::exp((c * t1)) * ((stan::math::pow((c * t1), 2) - ((2 * c)
      * t1)) + 2)) / stan::math::pow(c, 3)));
    local_scalar_t__ r = DUMMY_VAR__;
    current_statement__ = 67;
    r = (stan::math::exp((t1 / N)) / (2500 * N));
    current_statement__ = 68;
    return (r * output);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real int_p_L_divide_l(real, real, real, real, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>,
                              stan::math::disjunction<stan::is_autodiff<T4__>,
                                                      std::is_floating_point<T4__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
int_p_L_divide_l(const T0__& N, const T1__& t1, const T2__& t2, const T3__&
                 u, const T4__& v, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ c1 = DUMMY_VAR__;
    current_statement__ = 70;
    c1 = -(((v / 50) + (1 / N)));
    local_scalar_t__ c2 = DUMMY_VAR__;
    current_statement__ = 71;
    c2 = -(((u / 50) + (1 / N)));
    local_scalar_t__ k1 = DUMMY_VAR__;
    current_statement__ = 72;
    k1 = ((-(1) / (50 * N)) * (((stan::math::exp((c1 * t2)) * ((c1 * t2) -
      1)) / stan::math::pow(c1, 2)) - ((stan::math::exp((c1 * t1)) * ((c1 *
      t1) - 1)) / stan::math::pow(c1, 2))));
    local_scalar_t__ k2 = DUMMY_VAR__;
    current_statement__ = 73;
    k2 = ((1 / (50 * N)) * (((stan::math::exp((c2 * t2)) * ((c2 * t2) - 1)) /
      stan::math::pow(c2, 2)) - ((stan::math::exp((c2 * t1)) * ((c2 * t1) -
      1)) / stan::math::pow(c2, 2))));
    local_scalar_t__ r = DUMMY_VAR__;
    current_statement__ = 74;
    r = stan::math::exp((t1 / N));
    current_statement__ = 75;
    return (r * (k1 + k2));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real int_p_L_divide_l_limit(real, real, real, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
int_p_L_divide_l_limit(const T0__& N, const T1__& t, const T2__& u,
                       const T3__& v, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ cu = DUMMY_VAR__;
    current_statement__ = 77;
    cu = -(((1 / N) + (u / 50)));
    local_scalar_t__ cv = DUMMY_VAR__;
    current_statement__ = 78;
    cv = -(((1 / N) + (v / 50)));
    current_statement__ = 79;
    return (((-(1) / (50 * N)) * stan::math::exp((t / N))) *
           (((stan::math::exp((cu * t)) * ((cu * t) - 1)) /
           stan::math::pow(cu, 2)) - ((stan::math::exp((cv * t)) * ((cv * t)
           - 1)) / stan::math::pow(cv, 2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class baseA_admixture_model final : public model_base_crtp<baseA_admixture_model> {
 private:
  int N_obs;
  Eigen::Matrix<double,-1,1> u_data__;
  Eigen::Matrix<double,-1,1> v_data__;
  std::vector<int> number;
  std::vector<std::vector<int>> group;
  double length;
  Eigen::Map<Eigen::Matrix<double,-1,1>> u{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> v{nullptr, 0};
 public:
  ~baseA_admixture_model() {}
  baseA_admixture_model(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "baseA_admixture_model_namespace::baseA_admixture_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 55;
      context__.validate_dims("data initialization", "N_obs", "int",
        std::vector<size_t>{});
      N_obs = std::numeric_limits<int>::min();
      current_statement__ = 55;
      N_obs = context__.vals_i("N_obs")[(1 - 1)];
      current_statement__ = 55;
      stan::math::check_greater_or_equal(function__, "N_obs", N_obs, 0);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("u", "N_obs", N_obs);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "u", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      u_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                   std::numeric_limits<double>::quiet_NaN());
      new (&u) Eigen::Map<Eigen::Matrix<double,-1,1>>(u_data__.data(), N_obs);
      {
        std::vector<local_scalar_t__> u_flat__;
        current_statement__ = 57;
        u_flat__ = context__.vals_r("u");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(u, u_flat__[(pos__ - 1)],
            "assigning variable u", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "u", u, 0);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("v", "N_obs", N_obs);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "v", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      v_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                   std::numeric_limits<double>::quiet_NaN());
      new (&v) Eigen::Map<Eigen::Matrix<double,-1,1>>(v_data__.data(), N_obs);
      {
        std::vector<local_scalar_t__> v_flat__;
        current_statement__ = 59;
        v_flat__ = context__.vals_r("v");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(v, v_flat__[(pos__ - 1)],
            "assigning variable v", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "v", v, 0);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("number", "N_obs", N_obs);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "number", "int",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      number = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      current_statement__ = 61;
      number = context__.vals_i("number");
      current_statement__ = 62;
      stan::math::validate_non_negative_index("group", "N_obs", N_obs);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "group", "int",
        std::vector<size_t>{static_cast<size_t>(N_obs),
          static_cast<size_t>(2)});
      group = std::vector<std::vector<int>>(N_obs,
                std::vector<int>(2, std::numeric_limits<int>::min()));
      {
        std::vector<int> group_flat__;
        current_statement__ = 63;
        group_flat__ = context__.vals_i("group");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N_obs; ++sym2__) {
            stan::model::assign(group, group_flat__[(pos__ - 1)],
              "assigning variable group", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 64;
      context__.validate_dims("data initialization", "length", "double",
        std::vector<size_t>{});
      length = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 64;
      length = context__.vals_r("length")[(1 - 1)];
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 6 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "baseA_admixture_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = --filename-in-msg=baseA_admixture.stan"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "baseA_admixture_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> N =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(6, DUMMY_VAR__);
      current_statement__ = 1;
      N = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, 100000,
            lp__, 6);
      local_scalar_t__ T1 = DUMMY_VAR__;
      current_statement__ = 2;
      T1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1,
             lp__);
      local_scalar_t__ T2 = DUMMY_VAR__;
      current_statement__ = 3;
      T2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(T1,
             lp__);
      local_scalar_t__ T3 = DUMMY_VAR__;
      current_statement__ = 4;
      T3 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(T2,
             lp__);
      local_scalar_t__ fraction = DUMMY_VAR__;
      current_statement__ = 5;
      fraction = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      {
        current_statement__ = 8;
        for (int i = 1; i <= 6; ++i) {
          current_statement__ = 6;
          lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                           stan::model::rvalue(N, "N",
                             stan::model::index_uni(i)), 1, 100000));
        }
        current_statement__ = 9;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(T1, 1, 200));
        current_statement__ = 10;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(T2, T1, 500));
        current_statement__ = 11;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(T3, T2, 1000));
        current_statement__ = 12;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(fraction, 0, 1));
        current_statement__ = 54;
        for (int i = 1; i <= N_obs; ++i) {
          local_scalar_t__ lambda = DUMMY_VAR__;
          current_statement__ = 52;
          if ((stan::math::primitive_value(
                 stan::math::logical_eq(
                   stan::model::rvalue(
                     stan::model::rvalue(group, "group",
                       stan::model::index_uni(i)), "group[i]",
                     stan::model::index_uni(1)), 0))
              &&
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(
                    stan::model::rvalue(group, "group",
                      stan::model::index_uni(i)), "group[i]",
                    stan::model::index_uni(2)), 0)))) {
            current_statement__ = 49;
            lambda = ((int_p_L_divide_l(
                         stan::model::rvalue(N, "N",
                           stan::model::index_uni(1)),
                         static_cast<double>(0), T3,
                         stan::model::rvalue(u, "u",
                           stan::model::index_uni(i)),
                         stan::model::rvalue(v, "v",
                           stan::model::index_uni(i)), pstream__)
              +
              int_p_L_divide_l_limit(
                stan::model::rvalue(N, "N", stan::model::index_uni(6)), T3,
                stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                pstream__))
              * length);
            current_statement__ = 50;
            lp_accum__.add(stan::math::poisson_lpmf<false>(
                             stan::model::rvalue(number, "number",
                               stan::model::index_uni(i)), lambda));
          } else {
            current_statement__ = 48;
            if ((stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(
                       stan::model::rvalue(group, "group",
                         stan::model::index_uni(i)), "group[i]",
                       stan::model::index_uni(1)), 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(
                      stan::model::rvalue(group, "group",
                        stan::model::index_uni(i)), "group[i]",
                      stan::model::index_uni(2)), 1)))) {
              current_statement__ = 45;
              lambda = (((fraction *
                int_p_L_divide_l(
                  stan::model::rvalue(N, "N", stan::model::index_uni(1)), T1,
                  T3, stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                  stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                  pstream__))
                +
                int_p_L_divide_l_limit(
                  stan::model::rvalue(N, "N", stan::model::index_uni(6)), T3,
                  stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                  stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                  pstream__))
                * length);
              current_statement__ = 46;
              lp_accum__.add(stan::math::poisson_lpmf<false>(
                               stan::model::rvalue(number, "number",
                                 stan::model::index_uni(i)), lambda));
            } else {
              current_statement__ = 44;
              if ((stan::math::primitive_value(
                     stan::math::logical_eq(
                       stan::model::rvalue(
                         stan::model::rvalue(group, "group",
                           stan::model::index_uni(i)), "group[i]",
                         stan::model::index_uni(1)), 0))
                  &&
                  stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(
                        stan::model::rvalue(group, "group",
                          stan::model::index_uni(i)), "group[i]",
                        stan::model::index_uni(2)), 2)))) {
                current_statement__ = 41;
                lambda = (int_p_L_divide_l_limit(
                            stan::model::rvalue(N, "N",
                              stan::model::index_uni(6)), T3,
                            stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)),
                            stan::model::rvalue(v, "v",
                              stan::model::index_uni(i)), pstream__)
                  * length);
                current_statement__ = 42;
                lp_accum__.add(stan::math::poisson_lpmf<false>(
                                 stan::model::rvalue(number, "number",
                                   stan::model::index_uni(i)), lambda));
              } else {
                current_statement__ = 40;
                if ((stan::math::primitive_value(
                       stan::math::logical_eq(
                         stan::model::rvalue(
                           stan::model::rvalue(group, "group",
                             stan::model::index_uni(i)), "group[i]",
                           stan::model::index_uni(1)), 0))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_eq(
                        stan::model::rvalue(
                          stan::model::rvalue(group, "group",
                            stan::model::index_uni(i)), "group[i]",
                          stan::model::index_uni(2)), 3)))) {
                  current_statement__ = 37;
                  lambda = (int_p_L_divide_l_limit(
                              stan::model::rvalue(N, "N",
                                stan::model::index_uni(6)), T3,
                              stan::model::rvalue(u, "u",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(v, "v",
                                stan::model::index_uni(i)), pstream__)
                    * length);
                  current_statement__ = 38;
                  lp_accum__.add(stan::math::poisson_lpmf<false>(
                                   stan::model::rvalue(number, "number",
                                     stan::model::index_uni(i)), lambda));
                } else {
                  current_statement__ = 36;
                  if ((stan::math::primitive_value(
                         stan::math::logical_eq(
                           stan::model::rvalue(
                             stan::model::rvalue(group, "group",
                               stan::model::index_uni(i)), "group[i]",
                             stan::model::index_uni(1)), 1))
                      &&
                      stan::math::primitive_value(
                        stan::math::logical_eq(
                          stan::model::rvalue(
                            stan::model::rvalue(group, "group",
                              stan::model::index_uni(i)), "group[i]",
                            stan::model::index_uni(2)), 1)))) {
                    current_statement__ = 33;
                    lambda = ((((int_p_L_divide_l(
                                   stan::model::rvalue(N, "N",
                                     stan::model::index_uni(2)),
                                   static_cast<double>(0), T1,
                                   stan::model::rvalue(u, "u",
                                     stan::model::index_uni(i)),
                                   stan::model::rvalue(v, "v",
                                     stan::model::index_uni(i)), pstream__)
                      + (stan::math::pow(fraction, 2) *
                      int_p_L_divide_l(
                        stan::model::rvalue(N, "N", stan::model::index_uni(1)),
                        T1, T3,
                        stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                        stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                        pstream__)))
                      + (stan::math::pow((1 - fraction), 2) *
                      (int_p_L_divide_l(
                         stan::model::rvalue(N, "N",
                           stan::model::index_uni(3)), T1, T2,
                         stan::model::rvalue(u, "u",
                           stan::model::index_uni(i)),
                         stan::model::rvalue(v, "v",
                           stan::model::index_uni(i)), pstream__)
                      +
                      int_p_L_divide_l(
                        stan::model::rvalue(N, "N", stan::model::index_uni(5)),
                        T2, T3,
                        stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                        stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                        pstream__))))
                      +
                      int_p_L_divide_l_limit(
                        stan::model::rvalue(N, "N", stan::model::index_uni(6)),
                        T3,
                        stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                        stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                        pstream__))
                      * length);
                    current_statement__ = 34;
                    lp_accum__.add(stan::math::poisson_lpmf<false>(
                                     stan::model::rvalue(number, "number",
                                       stan::model::index_uni(i)), lambda));
                  } else {
                    current_statement__ = 32;
                    if ((stan::math::primitive_value(
                           stan::math::logical_eq(
                             stan::model::rvalue(
                               stan::model::rvalue(group, "group",
                                 stan::model::index_uni(i)), "group[i]",
                               stan::model::index_uni(1)), 1))
                        &&
                        stan::math::primitive_value(
                          stan::math::logical_eq(
                            stan::model::rvalue(
                              stan::model::rvalue(group, "group",
                                stan::model::index_uni(i)), "group[i]",
                              stan::model::index_uni(2)), 2)))) {
                      current_statement__ = 29;
                      lambda = ((((1 - fraction) *
                        (int_p_L_divide_l(
                           stan::model::rvalue(N, "N",
                             stan::model::index_uni(3)), T1, T2,
                           stan::model::rvalue(u, "u",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(v, "v",
                             stan::model::index_uni(i)), pstream__)
                        +
                        int_p_L_divide_l(
                          stan::model::rvalue(N, "N",
                            stan::model::index_uni(5)), T2, T3,
                          stan::model::rvalue(u, "u",
                            stan::model::index_uni(i)),
                          stan::model::rvalue(v, "v",
                            stan::model::index_uni(i)), pstream__)))
                        +
                        int_p_L_divide_l_limit(
                          stan::model::rvalue(N, "N",
                            stan::model::index_uni(6)), T3,
                          stan::model::rvalue(u, "u",
                            stan::model::index_uni(i)),
                          stan::model::rvalue(v, "v",
                            stan::model::index_uni(i)), pstream__))
                        * length);
                      current_statement__ = 30;
                      lp_accum__.add(stan::math::poisson_lpmf<false>(
                                       stan::model::rvalue(number, "number",
                                         stan::model::index_uni(i)), lambda));
                    } else {
                      current_statement__ = 28;
                      if ((stan::math::primitive_value(
                             stan::math::logical_eq(
                               stan::model::rvalue(
                                 stan::model::rvalue(group, "group",
                                   stan::model::index_uni(i)), "group[i]",
                                 stan::model::index_uni(1)), 1))
                          &&
                          stan::math::primitive_value(
                            stan::math::logical_eq(
                              stan::model::rvalue(
                                stan::model::rvalue(group, "group",
                                  stan::model::index_uni(i)), "group[i]",
                                stan::model::index_uni(2)), 3)))) {
                        current_statement__ = 25;
                        lambda = ((((1 - fraction) *
                          int_p_L_divide_l(
                            stan::model::rvalue(N, "N",
                              stan::model::index_uni(5)), T2, T3,
                            stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)),
                            stan::model::rvalue(v, "v",
                              stan::model::index_uni(i)), pstream__))
                          +
                          int_p_L_divide_l_limit(
                            stan::model::rvalue(N, "N",
                              stan::model::index_uni(6)), T3,
                            stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)),
                            stan::model::rvalue(v, "v",
                              stan::model::index_uni(i)), pstream__))
                          * length);
                        current_statement__ = 26;
                        lp_accum__.add(stan::math::poisson_lpmf<false>(
                                         stan::model::rvalue(number,
                                           "number",
                                           stan::model::index_uni(i)), lambda));
                      } else {
                        current_statement__ = 24;
                        if ((stan::math::primitive_value(
                               stan::math::logical_eq(
                                 stan::model::rvalue(
                                   stan::model::rvalue(group, "group",
                                     stan::model::index_uni(i)), "group[i]",
                                   stan::model::index_uni(1)), 2))
                            &&
                            stan::math::primitive_value(
                              stan::math::logical_eq(
                                stan::model::rvalue(
                                  stan::model::rvalue(group, "group",
                                    stan::model::index_uni(i)), "group[i]",
                                  stan::model::index_uni(2)), 2)))) {
                          current_statement__ = 21;
                          lambda = (((int_p_L_divide_l(
                                        stan::model::rvalue(N, "N",
                                          stan::model::index_uni(3)),
                                        static_cast<double>(0), T2,
                                        stan::model::rvalue(u, "u",
                                          stan::model::index_uni(i)),
                                        stan::model::rvalue(v, "v",
                                          stan::model::index_uni(i)),
                                        pstream__)
                            +
                            int_p_L_divide_l(
                              stan::model::rvalue(N, "N",
                                stan::model::index_uni(5)), T2, T3,
                              stan::model::rvalue(u, "u",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(v, "v",
                                stan::model::index_uni(i)), pstream__))
                            +
                            int_p_L_divide_l_limit(
                              stan::model::rvalue(N, "N",
                                stan::model::index_uni(6)), T3,
                              stan::model::rvalue(u, "u",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(v, "v",
                                stan::model::index_uni(i)), pstream__))
                            * length);
                          current_statement__ = 22;
                          lp_accum__.add(stan::math::poisson_lpmf<false>(
                                           stan::model::rvalue(number,
                                             "number",
                                             stan::model::index_uni(i)),
                                           lambda));
                        } else {
                          current_statement__ = 20;
                          if ((stan::math::primitive_value(
                                 stan::math::logical_eq(
                                   stan::model::rvalue(
                                     stan::model::rvalue(group, "group",
                                       stan::model::index_uni(i)),
                                     "group[i]", stan::model::index_uni(1)),
                                   3))
                              &&
                              stan::math::primitive_value(
                                stan::math::logical_eq(
                                  stan::model::rvalue(
                                    stan::model::rvalue(group, "group",
                                      stan::model::index_uni(i)), "group[i]",
                                    stan::model::index_uni(2)), 3)))) {
                            current_statement__ = 17;
                            lambda = (((int_p_L_divide_l(
                                          stan::model::rvalue(N, "N",
                                            stan::model::index_uni(4)),
                                          static_cast<double>(0), T2,
                                          stan::model::rvalue(u, "u",
                                            stan::model::index_uni(i)),
                                          stan::model::rvalue(v, "v",
                                            stan::model::index_uni(i)),
                                          pstream__)
                              +
                              int_p_L_divide_l(
                                stan::model::rvalue(N, "N",
                                  stan::model::index_uni(5)), T2, T3,
                                stan::model::rvalue(u, "u",
                                  stan::model::index_uni(i)),
                                stan::model::rvalue(v, "v",
                                  stan::model::index_uni(i)), pstream__))
                              +
                              int_p_L_divide_l_limit(
                                stan::model::rvalue(N, "N",
                                  stan::model::index_uni(6)), T3,
                                stan::model::rvalue(u, "u",
                                  stan::model::index_uni(i)),
                                stan::model::rvalue(v, "v",
                                  stan::model::index_uni(i)), pstream__))
                              * length);
                            current_statement__ = 18;
                            lp_accum__.add(stan::math::poisson_lpmf<false>(
                                             stan::model::rvalue(number,
                                               "number",
                                               stan::model::index_uni(i)),
                                             lambda));
                          } else {
                            current_statement__ = 14;
                            lambda = ((int_p_L_divide_l(
                                         stan::model::rvalue(N, "N",
                                           stan::model::index_uni(5)), T2,
                                         T3,
                                         stan::model::rvalue(u, "u",
                                           stan::model::index_uni(i)),
                                         stan::model::rvalue(v, "v",
                                           stan::model::index_uni(i)),
                                         pstream__)
                              +
                              int_p_L_divide_l_limit(
                                stan::model::rvalue(N, "N",
                                  stan::model::index_uni(6)), T3,
                                stan::model::rvalue(u, "u",
                                  stan::model::index_uni(i)),
                                stan::model::rvalue(v, "v",
                                  stan::model::index_uni(i)), pstream__))
                              * length);
                            current_statement__ = 15;
                            lp_accum__.add(stan::math::poisson_lpmf<false>(
                                             stan::model::rvalue(number,
                                               "number",
                                               stan::model::index_uni(i)),
                                             lambda));
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "baseA_admixture_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> N =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(6, DUMMY_VAR__);
      current_statement__ = 1;
      N = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, 100000,
            lp__, 6);
      local_scalar_t__ T1 = DUMMY_VAR__;
      current_statement__ = 2;
      T1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1,
             lp__);
      local_scalar_t__ T2 = DUMMY_VAR__;
      current_statement__ = 3;
      T2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(T1,
             lp__);
      local_scalar_t__ T3 = DUMMY_VAR__;
      current_statement__ = 4;
      T3 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(T2,
             lp__);
      local_scalar_t__ fraction = DUMMY_VAR__;
      current_statement__ = 5;
      fraction = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      {
        current_statement__ = 8;
        for (int i = 1; i <= 6; ++i) {
          current_statement__ = 6;
          lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                           stan::model::rvalue(N, "N",
                             stan::model::index_uni(i)), 1, 100000));
        }
        current_statement__ = 9;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(T1, 1, 200));
        current_statement__ = 10;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(T2, T1, 500));
        current_statement__ = 11;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(T3, T2, 1000));
        current_statement__ = 12;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(fraction, 0, 1));
        current_statement__ = 54;
        for (int i = 1; i <= N_obs; ++i) {
          local_scalar_t__ lambda = DUMMY_VAR__;
          current_statement__ = 52;
          if ((stan::math::primitive_value(
                 stan::math::logical_eq(
                   stan::model::rvalue(
                     stan::model::rvalue(group, "group",
                       stan::model::index_uni(i)), "group[i]",
                     stan::model::index_uni(1)), 0))
              &&
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(
                    stan::model::rvalue(group, "group",
                      stan::model::index_uni(i)), "group[i]",
                    stan::model::index_uni(2)), 0)))) {
            current_statement__ = 49;
            lambda = ((int_p_L_divide_l(
                         stan::model::rvalue(N, "N",
                           stan::model::index_uni(1)),
                         static_cast<double>(0), T3,
                         stan::model::rvalue(u, "u",
                           stan::model::index_uni(i)),
                         stan::model::rvalue(v, "v",
                           stan::model::index_uni(i)), pstream__)
              +
              int_p_L_divide_l_limit(
                stan::model::rvalue(N, "N", stan::model::index_uni(6)), T3,
                stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                pstream__))
              * length);
            current_statement__ = 50;
            lp_accum__.add(stan::math::poisson_lpmf<false>(
                             stan::model::rvalue(number, "number",
                               stan::model::index_uni(i)), lambda));
          } else {
            current_statement__ = 48;
            if ((stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(
                       stan::model::rvalue(group, "group",
                         stan::model::index_uni(i)), "group[i]",
                       stan::model::index_uni(1)), 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(
                      stan::model::rvalue(group, "group",
                        stan::model::index_uni(i)), "group[i]",
                      stan::model::index_uni(2)), 1)))) {
              current_statement__ = 45;
              lambda = (((fraction *
                int_p_L_divide_l(
                  stan::model::rvalue(N, "N", stan::model::index_uni(1)), T1,
                  T3, stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                  stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                  pstream__))
                +
                int_p_L_divide_l_limit(
                  stan::model::rvalue(N, "N", stan::model::index_uni(6)), T3,
                  stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                  stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                  pstream__))
                * length);
              current_statement__ = 46;
              lp_accum__.add(stan::math::poisson_lpmf<false>(
                               stan::model::rvalue(number, "number",
                                 stan::model::index_uni(i)), lambda));
            } else {
              current_statement__ = 44;
              if ((stan::math::primitive_value(
                     stan::math::logical_eq(
                       stan::model::rvalue(
                         stan::model::rvalue(group, "group",
                           stan::model::index_uni(i)), "group[i]",
                         stan::model::index_uni(1)), 0))
                  &&
                  stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(
                        stan::model::rvalue(group, "group",
                          stan::model::index_uni(i)), "group[i]",
                        stan::model::index_uni(2)), 2)))) {
                current_statement__ = 41;
                lambda = (int_p_L_divide_l_limit(
                            stan::model::rvalue(N, "N",
                              stan::model::index_uni(6)), T3,
                            stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)),
                            stan::model::rvalue(v, "v",
                              stan::model::index_uni(i)), pstream__)
                  * length);
                current_statement__ = 42;
                lp_accum__.add(stan::math::poisson_lpmf<false>(
                                 stan::model::rvalue(number, "number",
                                   stan::model::index_uni(i)), lambda));
              } else {
                current_statement__ = 40;
                if ((stan::math::primitive_value(
                       stan::math::logical_eq(
                         stan::model::rvalue(
                           stan::model::rvalue(group, "group",
                             stan::model::index_uni(i)), "group[i]",
                           stan::model::index_uni(1)), 0))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_eq(
                        stan::model::rvalue(
                          stan::model::rvalue(group, "group",
                            stan::model::index_uni(i)), "group[i]",
                          stan::model::index_uni(2)), 3)))) {
                  current_statement__ = 37;
                  lambda = (int_p_L_divide_l_limit(
                              stan::model::rvalue(N, "N",
                                stan::model::index_uni(6)), T3,
                              stan::model::rvalue(u, "u",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(v, "v",
                                stan::model::index_uni(i)), pstream__)
                    * length);
                  current_statement__ = 38;
                  lp_accum__.add(stan::math::poisson_lpmf<false>(
                                   stan::model::rvalue(number, "number",
                                     stan::model::index_uni(i)), lambda));
                } else {
                  current_statement__ = 36;
                  if ((stan::math::primitive_value(
                         stan::math::logical_eq(
                           stan::model::rvalue(
                             stan::model::rvalue(group, "group",
                               stan::model::index_uni(i)), "group[i]",
                             stan::model::index_uni(1)), 1))
                      &&
                      stan::math::primitive_value(
                        stan::math::logical_eq(
                          stan::model::rvalue(
                            stan::model::rvalue(group, "group",
                              stan::model::index_uni(i)), "group[i]",
                            stan::model::index_uni(2)), 1)))) {
                    current_statement__ = 33;
                    lambda = ((((int_p_L_divide_l(
                                   stan::model::rvalue(N, "N",
                                     stan::model::index_uni(2)),
                                   static_cast<double>(0), T1,
                                   stan::model::rvalue(u, "u",
                                     stan::model::index_uni(i)),
                                   stan::model::rvalue(v, "v",
                                     stan::model::index_uni(i)), pstream__)
                      + (stan::math::pow(fraction, 2) *
                      int_p_L_divide_l(
                        stan::model::rvalue(N, "N", stan::model::index_uni(1)),
                        T1, T3,
                        stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                        stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                        pstream__)))
                      + (stan::math::pow((1 - fraction), 2) *
                      (int_p_L_divide_l(
                         stan::model::rvalue(N, "N",
                           stan::model::index_uni(3)), T1, T2,
                         stan::model::rvalue(u, "u",
                           stan::model::index_uni(i)),
                         stan::model::rvalue(v, "v",
                           stan::model::index_uni(i)), pstream__)
                      +
                      int_p_L_divide_l(
                        stan::model::rvalue(N, "N", stan::model::index_uni(5)),
                        T2, T3,
                        stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                        stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                        pstream__))))
                      +
                      int_p_L_divide_l_limit(
                        stan::model::rvalue(N, "N", stan::model::index_uni(6)),
                        T3,
                        stan::model::rvalue(u, "u", stan::model::index_uni(i)),
                        stan::model::rvalue(v, "v", stan::model::index_uni(i)),
                        pstream__))
                      * length);
                    current_statement__ = 34;
                    lp_accum__.add(stan::math::poisson_lpmf<false>(
                                     stan::model::rvalue(number, "number",
                                       stan::model::index_uni(i)), lambda));
                  } else {
                    current_statement__ = 32;
                    if ((stan::math::primitive_value(
                           stan::math::logical_eq(
                             stan::model::rvalue(
                               stan::model::rvalue(group, "group",
                                 stan::model::index_uni(i)), "group[i]",
                               stan::model::index_uni(1)), 1))
                        &&
                        stan::math::primitive_value(
                          stan::math::logical_eq(
                            stan::model::rvalue(
                              stan::model::rvalue(group, "group",
                                stan::model::index_uni(i)), "group[i]",
                              stan::model::index_uni(2)), 2)))) {
                      current_statement__ = 29;
                      lambda = ((((1 - fraction) *
                        (int_p_L_divide_l(
                           stan::model::rvalue(N, "N",
                             stan::model::index_uni(3)), T1, T2,
                           stan::model::rvalue(u, "u",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(v, "v",
                             stan::model::index_uni(i)), pstream__)
                        +
                        int_p_L_divide_l(
                          stan::model::rvalue(N, "N",
                            stan::model::index_uni(5)), T2, T3,
                          stan::model::rvalue(u, "u",
                            stan::model::index_uni(i)),
                          stan::model::rvalue(v, "v",
                            stan::model::index_uni(i)), pstream__)))
                        +
                        int_p_L_divide_l_limit(
                          stan::model::rvalue(N, "N",
                            stan::model::index_uni(6)), T3,
                          stan::model::rvalue(u, "u",
                            stan::model::index_uni(i)),
                          stan::model::rvalue(v, "v",
                            stan::model::index_uni(i)), pstream__))
                        * length);
                      current_statement__ = 30;
                      lp_accum__.add(stan::math::poisson_lpmf<false>(
                                       stan::model::rvalue(number, "number",
                                         stan::model::index_uni(i)), lambda));
                    } else {
                      current_statement__ = 28;
                      if ((stan::math::primitive_value(
                             stan::math::logical_eq(
                               stan::model::rvalue(
                                 stan::model::rvalue(group, "group",
                                   stan::model::index_uni(i)), "group[i]",
                                 stan::model::index_uni(1)), 1))
                          &&
                          stan::math::primitive_value(
                            stan::math::logical_eq(
                              stan::model::rvalue(
                                stan::model::rvalue(group, "group",
                                  stan::model::index_uni(i)), "group[i]",
                                stan::model::index_uni(2)), 3)))) {
                        current_statement__ = 25;
                        lambda = ((((1 - fraction) *
                          int_p_L_divide_l(
                            stan::model::rvalue(N, "N",
                              stan::model::index_uni(5)), T2, T3,
                            stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)),
                            stan::model::rvalue(v, "v",
                              stan::model::index_uni(i)), pstream__))
                          +
                          int_p_L_divide_l_limit(
                            stan::model::rvalue(N, "N",
                              stan::model::index_uni(6)), T3,
                            stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)),
                            stan::model::rvalue(v, "v",
                              stan::model::index_uni(i)), pstream__))
                          * length);
                        current_statement__ = 26;
                        lp_accum__.add(stan::math::poisson_lpmf<false>(
                                         stan::model::rvalue(number,
                                           "number",
                                           stan::model::index_uni(i)), lambda));
                      } else {
                        current_statement__ = 24;
                        if ((stan::math::primitive_value(
                               stan::math::logical_eq(
                                 stan::model::rvalue(
                                   stan::model::rvalue(group, "group",
                                     stan::model::index_uni(i)), "group[i]",
                                   stan::model::index_uni(1)), 2))
                            &&
                            stan::math::primitive_value(
                              stan::math::logical_eq(
                                stan::model::rvalue(
                                  stan::model::rvalue(group, "group",
                                    stan::model::index_uni(i)), "group[i]",
                                  stan::model::index_uni(2)), 2)))) {
                          current_statement__ = 21;
                          lambda = (((int_p_L_divide_l(
                                        stan::model::rvalue(N, "N",
                                          stan::model::index_uni(3)),
                                        static_cast<double>(0), T2,
                                        stan::model::rvalue(u, "u",
                                          stan::model::index_uni(i)),
                                        stan::model::rvalue(v, "v",
                                          stan::model::index_uni(i)),
                                        pstream__)
                            +
                            int_p_L_divide_l(
                              stan::model::rvalue(N, "N",
                                stan::model::index_uni(5)), T2, T3,
                              stan::model::rvalue(u, "u",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(v, "v",
                                stan::model::index_uni(i)), pstream__))
                            +
                            int_p_L_divide_l_limit(
                              stan::model::rvalue(N, "N",
                                stan::model::index_uni(6)), T3,
                              stan::model::rvalue(u, "u",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(v, "v",
                                stan::model::index_uni(i)), pstream__))
                            * length);
                          current_statement__ = 22;
                          lp_accum__.add(stan::math::poisson_lpmf<false>(
                                           stan::model::rvalue(number,
                                             "number",
                                             stan::model::index_uni(i)),
                                           lambda));
                        } else {
                          current_statement__ = 20;
                          if ((stan::math::primitive_value(
                                 stan::math::logical_eq(
                                   stan::model::rvalue(
                                     stan::model::rvalue(group, "group",
                                       stan::model::index_uni(i)),
                                     "group[i]", stan::model::index_uni(1)),
                                   3))
                              &&
                              stan::math::primitive_value(
                                stan::math::logical_eq(
                                  stan::model::rvalue(
                                    stan::model::rvalue(group, "group",
                                      stan::model::index_uni(i)), "group[i]",
                                    stan::model::index_uni(2)), 3)))) {
                            current_statement__ = 17;
                            lambda = (((int_p_L_divide_l(
                                          stan::model::rvalue(N, "N",
                                            stan::model::index_uni(4)),
                                          static_cast<double>(0), T2,
                                          stan::model::rvalue(u, "u",
                                            stan::model::index_uni(i)),
                                          stan::model::rvalue(v, "v",
                                            stan::model::index_uni(i)),
                                          pstream__)
                              +
                              int_p_L_divide_l(
                                stan::model::rvalue(N, "N",
                                  stan::model::index_uni(5)), T2, T3,
                                stan::model::rvalue(u, "u",
                                  stan::model::index_uni(i)),
                                stan::model::rvalue(v, "v",
                                  stan::model::index_uni(i)), pstream__))
                              +
                              int_p_L_divide_l_limit(
                                stan::model::rvalue(N, "N",
                                  stan::model::index_uni(6)), T3,
                                stan::model::rvalue(u, "u",
                                  stan::model::index_uni(i)),
                                stan::model::rvalue(v, "v",
                                  stan::model::index_uni(i)), pstream__))
                              * length);
                            current_statement__ = 18;
                            lp_accum__.add(stan::math::poisson_lpmf<false>(
                                             stan::model::rvalue(number,
                                               "number",
                                               stan::model::index_uni(i)),
                                             lambda));
                          } else {
                            current_statement__ = 14;
                            lambda = ((int_p_L_divide_l(
                                         stan::model::rvalue(N, "N",
                                           stan::model::index_uni(5)), T2,
                                         T3,
                                         stan::model::rvalue(u, "u",
                                           stan::model::index_uni(i)),
                                         stan::model::rvalue(v, "v",
                                           stan::model::index_uni(i)),
                                         pstream__)
                              +
                              int_p_L_divide_l_limit(
                                stan::model::rvalue(N, "N",
                                  stan::model::index_uni(6)), T3,
                                stan::model::rvalue(u, "u",
                                  stan::model::index_uni(i)),
                                stan::model::rvalue(v, "v",
                                  stan::model::index_uni(i)), pstream__))
                              * length);
                            current_statement__ = 15;
                            lp_accum__.add(stan::math::poisson_lpmf<false>(
                                             stan::model::rvalue(number,
                                               "number",
                                               stan::model::index_uni(i)),
                                             lambda));
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "baseA_admixture_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> N =
        Eigen::Matrix<double,-1,1>::Constant(6,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      N = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1, 100000,
            lp__, 6);
      double T1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      T1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1,
             lp__);
      double T2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      T2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(T1,
             lp__);
      double T3 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      T3 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(T2,
             lp__);
      double fraction = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      fraction = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      out__.write(N);
      out__.write(T1);
      out__.write(T2);
      out__.write(T3);
      out__.write(fraction);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> N =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(6, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(N,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(6),
        "assigning variable N");
      out__.write_free_lub(1, 100000, N);
      local_scalar_t__ T1 = DUMMY_VAR__;
      current_statement__ = 2;
      T1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(1, T1);
      local_scalar_t__ T2 = DUMMY_VAR__;
      current_statement__ = 3;
      T2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(T1, T2);
      local_scalar_t__ T3 = DUMMY_VAR__;
      current_statement__ = 4;
      T3 = in__.read<local_scalar_t__>();
      out__.write_free_lb(T2, T3);
      local_scalar_t__ fraction = DUMMY_VAR__;
      current_statement__ = 5;
      fraction = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, fraction);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "N", "double",
        std::vector<size_t>{static_cast<size_t>(6)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "T1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "T2", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "T3", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "fraction",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> N =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(6, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> N_flat__;
        current_statement__ = 1;
        N_flat__ = context__.vals_r("N");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          stan::model::assign(N, N_flat__[(pos__ - 1)],
            "assigning variable N", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(1, 100000, N);
      local_scalar_t__ T1 = DUMMY_VAR__;
      current_statement__ = 2;
      T1 = context__.vals_r("T1")[(1 - 1)];
      out__.write_free_lb(1, T1);
      local_scalar_t__ T2 = DUMMY_VAR__;
      current_statement__ = 3;
      T2 = context__.vals_r("T2")[(1 - 1)];
      out__.write_free_lb(T1, T2);
      local_scalar_t__ T3 = DUMMY_VAR__;
      current_statement__ = 4;
      T3 = context__.vals_r("T3")[(1 - 1)];
      out__.write_free_lb(T2, T3);
      local_scalar_t__ fraction = DUMMY_VAR__;
      current_statement__ = 5;
      fraction = context__.vals_r("fraction")[(1 - 1)];
      out__.write_free_lb(0, fraction);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"N", "T1", "T2", "T3", "fraction"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(6)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
      param_names__.emplace_back(std::string() + "N" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "T1");
    param_names__.emplace_back(std::string() + "T2");
    param_names__.emplace_back(std::string() + "T3");
    param_names__.emplace_back(std::string() + "fraction");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
      param_names__.emplace_back(std::string() + "N" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "T1");
    param_names__.emplace_back(std::string() + "T2");
    param_names__.emplace_back(std::string() + "T3");
    param_names__.emplace_back(std::string() + "fraction");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"N\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(6) + "},\"block\":\"parameters\"},{\"name\":\"T1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"fraction\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"N\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(6) + "},\"block\":\"parameters\"},{\"name\":\"T1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"T3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"fraction\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((6 + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((6 + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = baseA_admixture_model_namespace::baseA_admixture_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return baseA_admixture_model_namespace::profiles__;
}
#endif